### ISSUE TITLE
Repeated keypresses

### ISSUE THREAD

**Issue by chang-zhao** [CribberSix/pygame-texteditor#6]
Hi CribberSix, thank you for this interesting tool.

Trying to use it, when I press for instance 'Backspace', I often get repeated keystrokes, so more than one symbol gets deleted. Maybe we should implement some kind of timed filtering for repeated key events?

Cheers. ;)

**Comment by chang-zhao** [comment]
What is the reason to use pygame.key.get_pressed() ?

https://www.pygame.org/docs/ref/key.html#pygame.key.get_pressed says that:

Note

Getting the list of pushed buttons with this function is not the proper way to handle text entry from the user. There is no way to know the order of keys pressed, and rapidly pushed keys can be completely unnoticed between two calls to pygame.key.get_pressed(). There is also no way to translate these pushed keys into a fully translated character value. See the pygame.KEYDOWN events on the pygame.eventpygame module for interacting with events and queues queue for this functionality.

**Comment by CribberSix** [comment]
I would definitely like to improve on the current state, but to be completely honest I am not sure when I will get around to it as I am on holiday soon + I'm moving in September. I will see - but if you want to tinker around with it and create PullRequests, you are more than welcome to!

I do remember having struggled with handling the input when a user "keeps pressing" a key.  It would certainly be worth an updated version on pypi as well.  Your suggestion of "timed filtering for repeated key events" might be hitting the nail on the head here.

**Comment by chang-zhao** [comment]
OK, I'll do some research myself, I think.

Firstly, it makes sense to imitate the system keyboard behavior:

- First key press => applied as soon as it happens.
- Then initial delay before repeating, like 250-333 ms. (If the event loop fires 60 times per second, then it's 15-20 cycles).
- Repeat rate 25-30 ms. (If one cycle is about 16 ms, then let's say it's 2 cycles per key input).

Secondly, perhaps only pygame.KEYDOWN should be used, no pygame.key.get_pressed().

Good luck with your life conditions. Enjoy good karma and create even more. ;)

**Comment by CribberSix** [comment]
I think the easiest solution for our problem might be using KEYDOWN (as you mentioned) in combination with `pygame.key.set_repeat(delay, interval)`. 

> "When the keyboard repeat is enabled, keys that are held down will generate multiple pygame.KEYDOWN events. The delay parameter is the number of milliseconds before the first repeated pygame.KEYDOWN event will be sent. After that, another pygame.KEYDOWN event will be sent every interval milliseconds." 

[Documentation source](http://www.pygame.org/docs/ref/key.html#pygame.key.set_repeat)

In your example: `pygame.key.set_repeat(delay=250, interval=25)`.

**Comment by CribberSix** [comment]
I looked into the issue and found a couple of things: 

1. I already used `pygame.KEYDOWN` for most keys. `pygame.key.get_pressed()` was only used for deletion with `K_BACKSPACE`, `K_DELETE` and the combination keys `K_LCTRL` & `K_RCTRL`.  All other inputs were already based on the event queue behind `KEYDOWN` which e.g. take the order of keys pressed into account. 
2. Implementing key repetition was thus as easy as adding `pygame.key.set_repeat(delay=250, interval=25)` to the instantiation method of the class. 
3. I revised the way `K_DELETE` and `K_BACKSPACE` was handled as the repeated deletions depended on frames, not on passed time which could have resulted in different time intervalls passing between deletions for different systems. I added it to the event queue now instead of it being handled separately to other keys.
4. So far, many keys with `len(pygame.key.name(event.key)) != 1` are not supported - the most common ones are implemented though (such as arrow keys for instance). Numpad wasn't yet, so I added it today as well. 

I uploaded it as version 0.6.6 to [pypi](https://pypi.org/project/pygame-texteditor/) in case you want to check it out.
